---
language: ruby
sudo: required
services: docker
notifications:
  slack: bloomberg-rnd:eHp3Czg42iGzaTgG8sAFeD9v
env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
before_install:
  - chef --version
  - eval "$(chef shell-init bash)"
  - cookstyle --version
  - foodcritic --version
install:
  - berks
  - chef gem install poise -v '~> 2.0'
  - chef gem install poise-boiler
before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142455888
  - sudo iptables -L DOCKER || sudo iptables -N DOCKER
jobs:
  include:
    - stage: verify
      script:
        - cookstyle
        - foodcritic .
    - stage: acceptance
      script:
        - chef exec kitchen converge
        - chef exec kitchen verify
      env:
        - CHEF_VERSION=13
        - CHEF_VERSION=14
cache:
  directories:
    - "$HOME/.berkshelf"
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk
branches:
  only:
    - master
matrix:
  fast_finish: true
