name 'lockrun'
maintainer 'John Bellone'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Installs lockrun executable for running cronjobs with overrun protection.'
long_description 'Installs lockrun executable for running cronjobs with overrun protection.'
version '1.1.0'

supports 'aix'
supports 'solaris2'
supports 'centos', '>= 5.4'
supports 'redhat', '>= 5.4'
supports 'ubuntu', '>= 12.04'

depends 'build-essential'
depends 'libarchive', '~> 0.6'
depends 'poise', '~> 2.0'
